In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import re
import warnings
warnings.filterwarnings('ignore',category = FutureWarning)
import seaborn as sns

In [3]:
sales_data = pd.read_csv(r"C:\Users\DELL\Desktop\course_prac\ml\Regression_Projects\Sales_project\sales_data.csv")

In [4]:
sales_data.head()

,system_calendar_key_N,product_id,sales_dollars_value,sales_units_value,sales_lbs_value
0,20160109,1,13927.0,934,18680
1,20160109,3,10289.0,1592,28646
2,20160109,4,357.0,22,440
3,20160109,6,23113.0,2027,81088
4,20160109,7,23177.0,3231,58164

In [5]:
sales_data.tail()

,system_calendar_key_N,product_id,sales_dollars_value,sales_units_value,sales_lbs_value
4526177,20181027,47536,8.0,2,3
4526178,20181027,47539,391.0,39,68
4526179,20181027,47543,105.0,59,48
4526180,20181027,47544,3720.0,1246,4361
4526181,20181027,47545,1729.0,2016,378

In [6]:
sales_data.shape

(4526182, 5)

In [7]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4526182 entries, 0 to 4526181
Data columns (total 5 columns):
 #   Column                 Dtype
---  ------                 -----
 0   system_calendar_key_N  int64
 1   product_id             int64
 2   sales_dollars_value    float64
 3   sales_units_value      int64
 4   sales_lbs_value        int64
dtypes: float64(1), int64(4)
memory usage: 172.7 MB

In [8]:
sales_data.isnull().sum()

system_calendar_key_N    0
product_id               0
sales_dollars_value      0
sales_units_value        0
sales_lbs_value          0
dtype: int64

In [12]:
sales_data.describe().T

,count,mean,std,min,25%,50%,75%,max
system_calendar_key_N,4526182.0,2.017505e+07,10735.371398,20160109.0,20161231.0,20171209.0,20181103.0,20191005.0
product_id,4526182.0,2.885857e+04,15312.536560,1.0,15069.0,29981.0,41513.0,57317.0
sales_dollars_value,4526182.0,2.159454e+04,78180.565626,0.0,523.0,2655.0,11765.0,4395964.0
sales_units_value,4526182.0,5.160053e+03,26853.407825,1.0,80.0,403.0,1807.0,873998.0
sales_lbs_value,4526182.0,1.715339e+04,127340.124381,0.0,86.0,611.0,3770.0,11003100.0

In [13]:
sales_data.describe()

,system_calendar_key_N,product_id,sales_dollars_value,sales_units_value,sales_lbs_value
count,4.526182e+06,4.526182e+06,4.526182e+06,4.526182e+06,4.526182e+06
mean,2.017505e+07,2.885857e+04,2.159454e+04,5.160053e+03,1.715339e+04
std,1.073537e+04,1.531254e+04,7.818057e+04,2.685341e+04,1.273401e+05
min,2.016011e+07,1.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00
25%,2.016123e+07,1.506900e+04,5.230000e+02,8.000000e+01,8.600000e+01
50%,2.017121e+07,2.998100e+04,2.655000e+03,4.030000e+02,6.110000e+02
75%,2.018110e+07,4.151300e+04,1.176500e+04,1.807000e+03,3.770000e+03
max,2.019100e+07,5.731700e+04,4.395964e+06,8.739980e+05,1.100310e+07

In [14]:
from datetime import datetime

In [15]:
#20181027 -- format='%Y%m%d'

#27012018 -- format='%d%m%Y'

#27-01-2018 -- format='%d-%m-%Y'

sales_data['system_calendar_key_N'] = pd.to_datetime(sales_data['system_calendar_key_N'],format = '%Y%m%d',errors = 'ignore')

In [16]:
print(sales_data.dtypes)

system_calendar_key_N    datetime64[ns]
product_id                        int64
sales_dollars_value             float64
sales_units_value                 int64
sales_lbs_value                   int64
dtype: object

In [17]:
sales_data.head()

,system_calendar_key_N,product_id,sales_dollars_value,sales_units_value,sales_lbs_value
0,2016-01-09,1,13927.0,934,18680
1,2016-01-09,3,10289.0,1592,28646
2,2016-01-09,4,357.0,22,440
3,2016-01-09,6,23113.0,2027,81088
4,2016-01-09,7,23177.0,3231,58164

In [18]:
google_search_data = pd.read_csv(r"C:\Users\DELL\Desktop\course_prac\ml\Regression_Projects\Sales_project\google_search_data.csv")

In [19]:
google_search_data.head()

         date platform  searchVolume  Claim_ID  week_number  year_new
0  05-01-2014   google           349       916            1      2014
1  06-01-2014   google           349       916            2      2014
2  07-01-2014   google           697       916            2      2014
3  10-01-2014   google           349       916            2      2014
4  20-01-2014   google           697       916            4      2014

In [20]:
google_search_data.tail()

              date platform  searchVolume  Claim_ID  week_number  year_new
181560  05-09-2019  walmart           125       980           36      2019
181561  22-09-2019  walmart            84       980           38      2019
181562  26-09-2019  walmart            42       980           39      2019
181563  15-07-2019  walmart            42       622           29      2019
181564  02-09-2019  walmart            42       689           36      2019

In [21]:
google_search_data.shape

(181565, 6)

In [22]:
google_search_data['platform'].value_counts()

platform
google     138115
amazon      23828
chewy       13352
walmart      6270
Name: count, dtype: int64

In [23]:
google_search_data['year_new'].value_counts()

year_new
2018    51388
2019    38682
2017    27399
2016    22280
2015    21372
2014    20444
Name: count, dtype: int64

In [24]:
google_search_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181565 entries, 0 to 181564
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   date          181565 non-null  object
 1   platform      181565 non-null  object
 2   searchVolume  181565 non-null  int64
 3   Claim_ID      181565 non-null  int64
 4   week_number   181565 non-null  int64
 5   year_new      181565 non-null  int64
dtypes: int64(4), object(2)
memory usage: 8.3+ MB

In [25]:
google_search_data['date'] = pd.to_datetime(google_search_data['date'],format = '%d-%m-%Y',errors = 'ignore')

In [26]:
google_search_data.head()

        date platform  searchVolume  Claim_ID  week_number  year_new
0 2014-01-05   google           349       916            1      2014
1 2014-01-06   google           349       916            2      2014
2 2014-01-07   google           697       916            2      2014
3 2014-01-10   google           349       916            2      2014
4 2014-01-20   google           697       916            4      2014

In [27]:
google_search_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181565 entries, 0 to 181564
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   date          181565 non-null  datetime64[ns]
 1   platform      181565 non-null  object
 2   searchVolume  181565 non-null  int64
 3   Claim_ID      181565 non-null  int64
 4   week_number   181565 non-null  int64
 5   year_new      181565 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 8.3+ MB

In [28]:
google_search_data.sort_values(by = 'date',inplace = True)

In [29]:
google_search_data.head()

            date platform  searchVolume  Claim_ID  week_number  year_new
1147  2014-01-01   google           889       922            1      2014
2365  2014-01-01   google           240       707            1      2014
3802  2014-01-01   google          1131       901            1      2014
13726 2014-01-01   google          1725       177            1      2014
1827  2014-01-01   google          2636       100            1      2014

In [30]:
google_search_data = google_search_data.reset_index(drop = True)

In [31]:
google_search_data.head()

        date platform  searchVolume  Claim_ID  week_number  year_new
0 2014-01-01   google           889       922            1      2014
1 2014-01-01   google           240       707            1      2014
2 2014-01-01   google          1131       901            1      2014
3 2014-01-01   google          1725       177            1      2014
4 2014-01-01   google          2636       100            1      2014

In [32]:
themes_product_data = pd.read_csv(r"C:\Users\DELL\Desktop\course_prac\ml\Regression_Projects\Sales_project\Theme_product_list.csv")

In [33]:
themes_product_data.head()

   PRODUCT_ID  CLAIM_ID
0           1         0
1           2         0
2           3         0
3           4         0
4           5         0

In [34]:
themes_product_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91485 entries, 0 to 91484
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PRODUCT_ID  91485 non-null  int64
 1   CLAIM_ID    91485 non-null  int64
dtypes: int64(2)
memory usage: 1.4 MB

In [35]:
themes_product_data.shape

(91485, 2)

In [37]:
social_media_data = pd.read_excel(r"C:\Users\DELL\Desktop\course_prac\ml\Regression_Projects\Sales_project\social_media_data.xlsx")

In [38]:
social_media_data.head()

   Theme Id       published_date  total_post
0     148.0  2015-01-10 00:00:00          76
1     148.0  2015-10-10 00:00:00          31
2     148.0  2015-11-10 00:00:00          65
3     148.0  2015-12-10 00:00:00          88
4     148.0           10/13/2015          85

In [39]:
social_media_data.tail()

        Theme Id       published_date  total_post
533385     876.0  2019-05-09 00:00:00        4658
533386     876.0  2019-06-09 00:00:00        3731
533387     876.0  2019-07-09 00:00:00        2336
533388     876.0  2019-08-09 00:00:00        1374
533389     876.0  2019-09-09 00:00:00        1442

In [40]:
social_media_data.shape

(533390, 3)

In [41]:
social_media_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 533390 entries, 0 to 533389
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Theme Id        314879 non-null  float64
 1   published_date  533390 non-null  object
 2   total_post      533390 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 12.2+ MB

In [42]:
social_media_data.isnull().sum()

Theme Id          218511
published_date         0
total_post             0
dtype: int64

In [44]:
social_media_data = social_media_data.dropna(subset=['Theme Id'])

In [45]:
social_media_data.shape

(314879, 3)

In [46]:
social_media_data.reset_index(drop=True, inplace=True)

In [47]:
social_media_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314879 entries, 0 to 314878
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Theme Id        314879 non-null  float64
 1   published_date  314879 non-null  object
 2   total_post      314879 non-null  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 7.2+ MB

In [50]:
social_media_data['Theme Id'] = social_media_data['Theme Id'].astype('int64')

In [51]:
social_media_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314879 entries, 0 to 314878
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Theme Id        314879 non-null  int64
 1   published_date  314879 non-null  object
 2   total_post      314879 non-null  int64
dtypes: int64(2), object(1)
memory usage: 7.2+ MB

In [53]:
product_manufacture_list = pd.read_csv(r"C:\Users\DELL\Desktop\course_prac\ml\Regression_Projects\Sales_project\product_manufacturer_list.csv")

In [54]:
product_manufacture_list.head()

,PRODUCT_ID,Vendor,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,1,Others,NaN,NaN,NaN,NaN,NaN
1,2,Others,NaN,NaN,NaN,NaN,NaN
2,3,Others,NaN,NaN,NaN,NaN,NaN
3,4,Others,NaN,NaN,NaN,NaN,NaN
4,5,Others,NaN,NaN,NaN,NaN,NaN

In [55]:
product_manufacture_list = product_manufacture_list[['PRODUCT_ID','Vendor']]

In [56]:
product_manufacture_list.head()

   PRODUCT_ID  Vendor
0           1  Others
1           2  Others
2           3  Others
3           4  Others
4           5  Others

In [57]:
product_manufacture_list.shape

(67175, 2)

In [58]:
product_manufacture_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67175 entries, 0 to 67174
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PRODUCT_ID  67175 non-null  int64
 1   Vendor      67175 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.0+ MB

In [59]:
themes_list = pd.read_csv(r"C:\Users\DELL\Desktop\course_prac\ml\Regression_Projects\Sales_project\Theme_list.csv")

In [60]:
themes_list.head()

   CLAIM_ID Claim Name
0         0   No Claim
1         8   low carb
2        15      beans
3        16      cocoa
4        26    vanilla

In [61]:
themes_list.shape

(208, 2)

In [62]:
themes_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CLAIM_ID    208 non-null    int64
 1   Claim Name  208 non-null    object
dtypes: int64(1), object(1)
memory usage: 3.4+ KB

In [63]:
themes_list['CLAIM_ID'].nunique()

208

In [68]:
themes_list['CLAIM_ID'].unique()

array([  0,   8,  15,  16,  26,  32,  38,  39,  40,  58,  59,  65,  73,
        75,  79,  80,  81, 100, 101, 120, 125, 138, 139, 142, 143, 144,
       145, 147, 148, 151, 152, 157, 158, 163, 171, 173, 177, 178, 185,
       186, 187, 191, 192, 193, 197, 207, 211, 220, 222, 224, 227, 228,
       287, 384, 385, 388, 393, 430, 432, 433, 437, 438, 440, 441, 916,
       650, 713, 979, 620, 543, 904, 754, 821, 984, 777, 670, 761, 780,
       941, 832, 608, 681, 913, 622, 738, 600, 601, 788, 867, 977, 928,
       813, 847, 702, 587, 842, 823, 743, 907, 974, 510, 747, 884, 931,
       803, 526, 860, 869, 870, 852, 541, 839, 634, 789, 618, 519, 576,
       844, 583, 606, 918, 716, 594, 889, 980, 930, 616, 901, 982, 556,
       741, 682, 558, 965, 657, 536, 507, 516, 981, 816, 555, 707, 944,
       903, 999, 677, 782, 959, 566, 659, 704, 915, 605, 632, 668, 732,
       770, 877, 958, 900, 970, 531, 929, 684, 967, 985, 964, 755, 683,
       799, 843, 948, 887, 937, 908, 737, 613, 615, 509, 922, 785, 946,
       720, 689, 567, 514, 574, 906, 517, 585, 960, 868, 957, 873, 552,
       529, 919, 776, 593, 983, 673, 963, 727, 508, 769, 949, 521, 876])

In [67]:
themes_list['Claim Name'].nunique()

208

In [69]:
themes_list['Claim Name'].unique()

array(['No Claim', 'low carb', 'beans', 'cocoa', 'vanilla', 'stroganoff',
       'cumin', 'high/source of protein', 'no additives/preservatives',
       'buckwheat', 'tutti frutti', 'ethical - not specific', 'brown ale',
       'french bisque', 'pheasant', 'whitebait', 'gmo free',
       'low calorie', 'peach', 'crab', 'nuts', 'venison', 'fruit',
       'convenience - easy-to-prepare', 'anchovy', 'pomegranate',
       'scallop', 'american gumbo', 'tuna', 'low sodium', 'low sugar',
       'french', 'chicken', 'ethical - packaging', 'cherry',
       'vitamin/mineral fortified', 'liver', 'red raspberry', 'cookie',
       'pollock', 'blueberry', 'bone health', 'prebiotic', 'poultry',
       'cheddar cheese', 'energy/alertness', 'halal', 'herbs', 'pizza',
       'american southwest style', 'salmon', 'beef hamburger', 'tilapia',
       'mackerel', 'peanut', 'lobster', 'sea salt', 'soy foods',
       'apple cinnamon', 'gingerbread', 'vegetarian', 'ethnic & exotic',
       'cream', 'berry', 'gluten free', 'added calcium', 'added fiber',
       'added iron', 'added protein', 'allergy', 'anti-aging/aging-well',
       'antioxidant', 'bacon', 'banana', 'beef', 'boar', 'brain health',
       'broccoli', 'butter', 'carob', 'carrot', 'cashew nut', 'celery',
       'cheese', 'chili', 'choice', 'cinnamon', 'co-branding', 'coconut',
       'cod', 'convenience', 'convenience - consumption',
       'convenience - packaging', 'convenience - ready prepared',
       'convenience - time saving', 'cranberry', 'crawfish',
       'dandelion greens', 'dha', 'diabetic', 'digestive/gut health',
       'dry', 'duck', 'economy', 'egg', 'ethical',
       'ethical - animal/fish & bird', 'ethical - environment',
       'ethical - human', 'eye health', 'fish',
       'functional, not specified', 'garden pea', 'green bean',
       'green tea', 'health (active)', 'health (passive)', 'heart health',
       'heart meat', 'hemp seeds', 'herbal', 'herring', 'hfcs free',
       'high/source of fiber', 'honey', 'immune health',
       'indulgent & premium', 'joint health', 'kale', 'kosher',
       'lactose free', 'lamb', 'low cholesterol', 'low fat', 'low gi',
       'mango', 'meat', 'microwaveable', 'milk chocolate', 'mint',
       'natural', 'no added sugar', 'no trans fats', 'omega-3',
       'oral health', 'orange', 'organic', 'others', 'parmesan cheese',
       'parsley', 'peanut butter', 'peppermint', 'pleasure', 'pork',
       'probiotic', 'pumpkin', 'rabbit', 'red apple', 'refill',
       'ricotta cheese', 'roquefort cheese', 'sardine', 'sausage',
       'seafood', 'seasonal/in-out products', 'seeds', 'shrimp',
       'single shot', 'skin health', 'smoked', 'snickerdoodle', 'sole',
       'spinach', 'sports & recovery', 'sticks', 'strawberry',
       'sugar free', 'sweet potato', 'toffee', 'traditional', 'trout',
       'turkey', 'vegan', 'vegetables', 'weight management',
       'white cheddar cheese', 'wholegrain', 'yogurt', 'brownie',
       'garlic', 'red tomato', 'cloves', 'rosemary', 'butterscotch',
       'pepper', 'quail', 'butternut squash', 'hickory smoked', 'dill',
       'papaya', 'blackberry', 'tarragon', 'seaweed', 'cola',
       'shortbread', 'passion fruit', 'blood orange', 'caramel'],
      dtype=object)

In [70]:
sales_data.head(2)

,system_calendar_key_N,product_id,sales_dollars_value,sales_units_value,sales_lbs_value
0,2016-01-09,1,13927.0,934,18680
1,2016-01-09,3,10289.0,1592,28646

In [71]:
social_media_data.head(2)

   Theme Id       published_date  total_post
0       148  2015-01-10 00:00:00          76
1       148  2015-10-10 00:00:00          31

In [72]:
social_media_data.rename(columns={'Theme Id':'CLAIM_ID'},inplace = True)

In [73]:
social_media_data.head(2)

   CLAIM_ID       published_date  total_post
0       148  2015-01-10 00:00:00          76
1       148  2015-10-10 00:00:00          31

In [74]:
sales_data.rename(columns={'product_id':'PRODUCT_ID'},inplace =True)

In [75]:
sales_data.head(2)

,system_calendar_key_N,PRODUCT_ID,sales_dollars_value,sales_units_value,sales_lbs_value
0,2016-01-09,1,13927.0,934,18680
1,2016-01-09,3,10289.0,1592,28646

In [76]:
google_search_data.rename(columns={"Claim_ID":"CLAIM_ID"}, inplace=True)

In [77]:
google_search_data.head(2)

        date platform  searchVolume  CLAIM_ID  week_number  year_new
0 2014-01-01   google           889       922            1      2014
1 2014-01-01   google           240       707            1      2014

In [78]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4526182 entries, 0 to 4526181
Data columns (total 5 columns):
 #   Column                 Dtype
---  ------                 -----
 0   system_calendar_key_N  datetime64[ns]
 1   PRODUCT_ID             int64
 2   sales_dollars_value    float64
 3   sales_units_value      int64
 4   sales_lbs_value        int64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 172.7 MB

In [79]:
google_search_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181565 entries, 0 to 181564
Data columns (total 6 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   date          181565 non-null  datetime64[ns]
 1   platform      181565 non-null  object
 2   searchVolume  181565 non-null  int64
 3   CLAIM_ID      181565 non-null  int64
 4   week_number   181565 non-null  int64
 5   year_new      181565 non-null  int64
dtypes: datetime64[ns](1), int64(4), object(1)
memory usage: 8.3+ MB

In [80]:
themes_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CLAIM_ID    208 non-null    int64
 1   Claim Name  208 non-null    object
dtypes: int64(1), object(1)
memory usage: 3.4+ KB

In [81]:
social_media_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 314879 entries, 0 to 314878
Data columns (total 3 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   CLAIM_ID        314879 non-null  int64
 1   published_date  314879 non-null  object
 2   total_post      314879 non-null  int64
dtypes: int64(2), object(1)
memory usage: 7.2+ MB

In [82]:
product_manufacture_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67175 entries, 0 to 67174
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PRODUCT_ID  67175 non-null  int64
 1   Vendor      67175 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.0+ MB

In [83]:
themes_product_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91485 entries, 0 to 91484
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   PRODUCT_ID  91485 non-null  int64
 1   CLAIM_ID    91485 non-null  int64
dtypes: int64(2)
memory usage: 1.4 MB

In [84]:
sales_product_mfg = pd.merge(sales_data,product_manufacture_list,how='left',on='PRODUCT_ID')

In [85]:
sales_product_mfg.head()

,system_calendar_key_N,PRODUCT_ID,sales_dollars_value,sales_units_value,sales_lbs_value,Vendor
0,2016-01-09,1,13927.0,934,18680,Others
1,2016-01-09,3,10289.0,1592,28646,Others
2,2016-01-09,4,357.0,22,440,Others
3,2016-01-09,6,23113.0,2027,81088,Others
4,2016-01-09,7,23177.0,3231,58164,Others

In [86]:
sales_product_mfg.shape

(4526182, 6)

In [87]:
sales_product_mfg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4526182 entries, 0 to 4526181
Data columns (total 6 columns):
 #   Column                 Dtype
---  ------                 -----
 0   system_calendar_key_N  datetime64[ns]
 1   PRODUCT_ID             int64
 2   sales_dollars_value    float64
 3   sales_units_value      int64
 4   sales_lbs_value        int64
 5   Vendor                 object
dtypes: datetime64[ns](1), float64(1), int64(3), object(1)
memory usage: 207.2+ MB

In [88]:
sales_product_mfg.isnull().sum()

system_calendar_key_N    0
PRODUCT_ID               0
sales_dollars_value      0
sales_units_value        0
sales_lbs_value          0
Vendor                   0
dtype: int64

In [89]:
sales_product_mfg_themes = pd.merge(sales_product_mfg,themes_product_data,how='left',on='PRODUCT_ID')

In [90]:
sales_product_mfg_themes.head()

,system_calendar_key_N,PRODUCT_ID,sales_dollars_value,sales_units_value,sales_lbs_value,Vendor,CLAIM_ID
0,2016-01-09,1,13927.0,934,18680,Others,0
1,2016-01-09,3,10289.0,1592,28646,Others,0
2,2016-01-09,4,357.0,22,440,Others,0
3,2016-01-09,6,23113.0,2027,81088,Others,0
4,2016-01-09,7,23177.0,3231,58164,Others,0

In [91]:
sales_product_mfg_themes.shape

(7767420, 7)

In [93]:
themes_product_data['PRODUCT_ID'].nunique()

57317

In [94]:
themes_product_data['PRODUCT_ID'].value_counts().head(10)

PRODUCT_ID
28135    14
18685    14
27076    14
27051    14
28136    14
18735    14
27053    14
18693    14
18713    14
18718    14
Name: count, dtype: int64

In [95]:
sales_product_mfg_themes.isnull().sum()

system_calendar_key_N    0
PRODUCT_ID               0
sales_dollars_value      0
sales_units_value        0
sales_lbs_value          0
Vendor                   0
CLAIM_ID                 0
dtype: int64

In [96]:
sales_product_mfg_themes['CLAIM_ID'].value_counts()

CLAIM_ID
0      2045703
8      1668808
40      826406
432     520679
32      387999
186     338116
224     218897
187     218897
81      215635
58      175912
222     146173
185     146173
438     132719
120     129212
227      84542
158      73382
151      60132
430      55961
75       42655
15       35758
220      26954
16       26367
73       25085
39       24818
433      22113
100      17795
125      16617
437      12152
147      11514
163      10967
193       8539
142       8208
145       7016
152       6117
207       5038
228       4485
287       4216
192       1001
101        956
171        827
385        824
384        726
191        598
178        264
38         150
211        138
393        112
65          61
148          3
Name: count, dtype: int64

In [97]:
sales_product_mfg_themes_name = pd.merge(sales_product_mfg_themes,themes_list,how='left',on='CLAIM_ID')

In [98]:
sales_product_mfg_themes_name.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7767420 entries, 0 to 7767419
Data columns (total 8 columns):
 #   Column                 Dtype
---  ------                 -----
 0   system_calendar_key_N  datetime64[ns]
 1   PRODUCT_ID             int64
 2   sales_dollars_value    float64
 3   sales_units_value      int64
 4   sales_lbs_value        int64
 5   Vendor                 object
 6   CLAIM_ID               int64
 7   Claim Name             object
dtypes: datetime64[ns](1), float64(1), int64(4), object(2)
memory usage: 474.1+ MB

In [99]:
sales_product_mfg_themes_name.isnull().sum()

system_calendar_key_N    0
PRODUCT_ID               0
sales_dollars_value      0
sales_units_value        0
sales_lbs_value          0
Vendor                   0
CLAIM_ID                 0
Claim Name               0
dtype: int64

In [101]:
sales_product_mfg_themes_name.shape

(7767420, 8)

In [100]:
sales_product_mfg_themes_name['Claim Name'].value_counts()

Claim Name
No Claim                         2045703
low carb                         1668808
no additives/preservatives        826406
apple cinnamon                    520679
stroganoff                        387999
pollock                           338116
american southwest style          218897
blueberry                         218897
gmo free                          215635
buckwheat                         175912
pizza                             146173
cookie                            146173
ethnic & exotic                   132719
crab                              129212
salmon                             84542
chicken                            73382
low sodium                         60132
soy foods                          55961
french bisque                      42655
beans                              35758
herbs                              26954
cocoa                              26367
brown ale                          25085
high/source of protein             24818
gingerbread                        22113
low calorie                        17795
nuts                               16617
vegetarian                         12152
american gumbo                     11514
ethical - packaging                10967
poultry                             8539
convenience - easy-to-prepare       8208
scallop                             7016
low sugar                           6117
energy/alertness                    5038
beef hamburger                      4485
tilapia                             4216
prebiotic                           1001
peach                                956
cherry                               827
peanut                               824
mackerel                             726
bone health                          598
red raspberry                        264
cumin                                150
halal                                138
sea salt                             112
ethical - not specific                61
tuna                                   3
Name: count, dtype: int64

In [102]:
sales_product_mfg_themes_name.head()

,system_calendar_key_N,PRODUCT_ID,sales_dollars_value,sales_units_value,sales_lbs_value,Vendor,CLAIM_ID,Claim Name
0,2016-01-09,1,13927.0,934,18680,Others,0,No Claim
1,2016-01-09,3,10289.0,1592,28646,Others,0,No Claim
2,2016-01-09,4,357.0,22,440,Others,0,No Claim
3,2016-01-09,6,23113.0,2027,81088,Others,0,No Claim
4,2016-01-09,7,23177.0,3231,58164,Others,0,No Claim

In [107]:
base_dataset = sales_product_mfg_themes_name[((sales_product_mfg_themes_name['Claim Name'] == 'No Claim')|
                                              (sales_product_mfg_themes_name['Claim Name'] == 'low carb')|
                                              (sales_product_mfg_themes_name['Claim Name'] == 'no additives/preservatives'))]

In [108]:
base_dataset.shape

(4540917, 8)

In [109]:
base_dataset['Claim Name'].value_counts()

Claim Name
No Claim                      2045703
low carb                      1668808
no additives/preservatives     826406
Name: count, dtype: int64